# Generated by Django 3.2.12 on 2022-03-13 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0005_auto_20160630_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about city.', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about listing.', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listingtype',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about profile.', null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_contact',
            field=models.CharField(max_length=30, null=True, verbose_name='Preferred Contact'),
        ),
    ]
