# Generated by Django 3.2.12 on 2022-03-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0005_auto_20160630_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about city.', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='listing',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about listing.', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about profile.', null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_contact',
            field=models.CharField(max_length=30, null=True, verbose_name='Preferred Contact'),
        ),
    ]
